// export const GET_INFO_SEARCH_STAFF_DATA = "GET_INFO_SEARCH_STAFF_DATA"

//modalWindow
    export const CLOSE_MODAL_WINDOW = "CLOSE_MODAL_WINDOW";

//Category
    //categoryAction    
    export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
    export const CATEGORY_REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
    export const CATEGORY_REQUEST_FAIL = "CATEGORY_REQUEST_FAIL";
    export const POD_CATEGORY = "POD_CATEGORY";

    //addNewCategoryAction
    export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";
    export const ADD_NEW_CATEGORY_REQUEST_SUCCESS = "ADD_NEW_CATEGORY_REQUEST_SUCCESS";
    export const ADD_NEW_CATEGORY_REQUEST_FAIL = "ADD_NEW_CATEGORY_REQUEST_FAIL";

    //getStaffByCategoryIdAction
    export const CATEGORY_REQUEST_BY_ID = "CATEGORY_REQUEST_BY_ID";
    export const CATEGORY_REQUEST_SUCCESS_BY_ID = "CATEGORY_REQUEST_SUCCESS_BY_ID";
    export const CATEGORY_REQUEST_FAIL_BY_ID = "CATEGORY_REQUEST_FAIL_BY_ID";

//Staff
    //staffAction
    export const GET_STAFF_INFO_DATA = "GET_STAFF_INFO_DATA";
    export const STAFF_REQUEST = "STAFF_REQUEST";
    export const STAFF_REQUEST_SUCCESS = "STAFF_REQUEST_SUCCESS";
    export const STAFF_REQUEST_FAIL = "STAFF_REQUEST_FAIL";

    //addNewStaffAction
    export const ADD_NEW_STAFF_REQUEST = "ADD_NEW_STAFF_REQUEST";
    export const ADD_NEW_STAFF_REQUEST_SUCCESS = "ADD_NEW_STAFF_REQUEST_SUCCESS";
    export const ADD_NEW_STAFF_REQUEST_FAIL = "ADD_NEW_STAFF_REQUEST_FAIL";
    export const PUSH_NEW_PHOTO_REQUEST = "PUSH_NEW_PHOTO_REQUEST";
    export const PUSH_NEW_PHOTO_REQUEST_SUCCESS = "PUSH_NEW_PHOTO_REQUEST_SUCCESS";
    export const PUSH_NEW_PHOTO_REQUEST_FAIL = "PUSH_NEW_PHOTO_REQUEST_FAIL";
    export const BASE_64_REQUEST = "BASE_64_REQUEST";
    export const BASE1_64_REQUEST = "BASE1_64_REQUEST";
    export const BASE2_64_REQUEST = "BASE2_64_REQUEST";
    export const BASE3_64_REQUEST = "BASE3_64_REQUEST";
    //addNewStaffAction(PUT)
    export const INPUT_CHANGE_VALUE = "INPUT_CHANGE_VALUE";
    export const INPUT_CHANGE_VALUE1 = "INPUT_CHANGE_VALUE1";
    export const INPUT_CHANGE_VALUE2 = "INPUT_CHANGE_VALUE2";
    export const INPUT_CHANGE_VALUE3 = "INPUT_CHANGE_VALUE3";
    export const EDIT_STAFF_REQUEST = "EDIT_STAFF_REQUEST";
    export const EDIT_STAFF_REQUEST_SUCCESS = "EDIT_STAFF_REQUEST_SUCCESS";
    export const EDIT_STAFF_REQUEST_FAIL = "EDIT_STAFF_REQUEST_FAIL";

    //searchStaffAction
    export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
    export const SEARCH_STAFF_REQUEST = "SEARCH_STAFF_REQUEST";
    export const SEARCH_STAFF_REQUEST_SUCCESS = "SEARCH_STAFF_REQUEST_SUCCESS";
    export const SEARCH_STAFF_REQUEST_FAIL = "SEARCH_STAFF_REQUEST_FAIL";

    //getStaffByIdAction
    export const STAFF_REQUEST_BY_ID = "STAFF_REQUEST_BY_ID";
    export const STAFF_REQUEST_SUCCESS_BY_ID = "STAFF_REQUEST_SUCCESS_BY_ID";
    export const STAFF_REQUEST_FAIL_BY_ID = "STAFF_REQUEST_FAIL_BY_ID";

    //searchStaffByIdAction
    export const SEARCH_STAFF_REQUEST_BY_ID = "SEARCH_STAFF_REQUEST_BY_ID";
    export const SEARCH_STAFF_REQUEST_SUCCESS_BY_ID = "SEARCH_STAFF_REQUEST_SUCCESS_BY_ID";
    export const SEARCH_STAFF_REQUEST_FAIL_BY_ID = "SEARCH_STAFF_REQUEST_FAIL_BY_ID";

//User
    //usersAuthAction
    export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
    export const USER_AUTH_REQUEST_SUCCESS = "USER_AUTH_REQUEST_SUCCESS";
    export const USER_AUTH_REQUEST_FAIL = "USER_AUTH_REQUEST_FAIL";
    
    //usersRegistrAction
    export const USER_REG_REQUEST = "USER_REG_REQUEST";
    export const USER_REG_REQUEST_SUCCESS = "USER_REG_REQUEST_SUCCESS";
    export const USER_REG_REQUEST_FAIL = "USER_REG_REQUEST_FAIL";

    //getUsersById
    export const USER_AUTH_REQUEST_BY_ID = "USER_AUTH_REQUEST_BY_ID";
    export const USER_AUTH_REQUEST_SUCCESS_BY_ID = "USER_AUTH_REQUEST_SUCCESS_BY_ID";
    export const USER_AUTH_REQUEST_FAIL_BY_ID = "USER_AUTH_REQUEST_FAIL_BY_ID";
    export const GET_PARAMS = "GET_PARAMS";


    export const DELETE_STAFF = "DELETE_STAFF"